### ISSUE TITLE
Add links to changesets

### ISSUE THREAD

**Issue by lizzard** [gijsk/diditland#2]
I haven't thought through why this would be useful other than to feel reassured the answer is correct, but it would be neat anyway.  The changesets could easily link to the hg repositories for each version. So for the example I just looked at, bug 1228230, I get: 

No
beta tag: FIREFOX_43_0b8_RELEASE
mozilla-inbound: hashes 63946a132b19 landed.
mozilla-central: hashes 63946a132b19 landed.

So for example, the m-c changeset could link to https://hg.mozilla.org/mozilla-central/rev/63946a132b19.

**Comment by gijsk** [comment]
It's only taken like 4 and a bit years, but I just fixed this. Woo!
